use hr_info;
set autocommit=0;
select * from employees;
delete from employees;
commit;
insert into employees values(1,'name1',null);
savepoint a1;
insert into employees values(2,'name2',null);
savepoint a2;
insert into employees values(3,'name3',null);
savepoint a3;
insert into employees values(4,'name4',null);
savepoint a4;
delete from employees;
rollback to savepoint a4;
rollback to savepoint a3;
rollback to savepoint a1;
rollback to savepoint a2;
select * from employees;
delete from employees;
rollback;
truncate table employees;
rollback;
