create database hr_info;
create database student;
use hr_info;
create table employees (empid int, name varchar(20), doj date);
describe employees;
alter table employees add salary int;
alter table employees add (phone_no int, mail_id varchar(33));
alter table employees add alt_phone_no int after phone_no;
alter table employees add sr_no int first;
alter table employees modify empid char(10);
alter table employees modify mail_id varchar(20);
alter table employees modify phone_no int after mail_id;
alter table employees rename column empid to empno;
alter table employees drop column sr_no;
alter table employees drop empno;
show tables;
desc employees;
RENAME TABLE EMPLOYEES TO EMP_INFO;
DROP TABLE EMP_INFO;