create table employees (empid int, name varchar(20), doj date);
insert into employees values(1, 'Sanjana', '2024-10-24');
select * from employees; 
insert into employees (empid, name) values(2, 'Sam');
insert into employees values(3, 'Alex', null);
insert into employees values(4, 'Priya',current_date());
insert into employees values(5, 'Scott',null),(6,'Allen','2021-09-10');
update employees set name= 'Suraj' where empid=1;
update employees set doj='2019-12-01' where empid>3;
update employees set name='abc';
delete from employees where empid=1;
delete from employees where empid>3;
delete from employees ;
insert into employees values(1, 'Sanjana',null);
set autocommit=0;
insert into employees values(2, 'Sanjana',null);
rollback;
insert into employees values(2, 'Sanjana',null);
insert into employees values(3, 'Sanjana',null);
commit;
rollback;
delete from employees;
rollback;