select replace('renu','r','z');
select replace(ename,'S','A') as report,ename from emp;
select reverse(ename),ename from emp;
select trim(' hello ');
select length(trim('hello'));
select now();
select current_date(),current_time();
select year(now());
select month(now());
select monthname(now());
select day(now());
select dayname(now());
select current_timestamp();
select date_add(now(), interval 1 day);
select date_add(now(), interval 10 day);
select date_add(now(), interval 1 month);
select date_add(now(), interval 1 year);
select date_add(now(), interval -1 month);
select date_sub(now(), interval 1 month);
select dayofweek(now());
insert into emp (empno,ename,hiredate) values (12,'Renu',str_to_date('12-dec-2021','%d-%b-%Y'));
select * from emp;
select date_format(now(),'%M');
select date_format(now(),'%m');
select date_format(now(),'%Y');
select date_format(now(),'%y');
select date_format(now(),'%d');
select date_format(now(),'%D');
select date_format(now(),'%W');
select date_format(now(),'%w');#dont follow this format
select date_format(now(),'%b');
select date_format(now(),'%a');
select str_to_date('12-dec-2021','%d-%b-%Y');
delete from emp where empno=12;
select count(empno),year(hiredate)
from emp
group by year(hiredate);
select * from emp where dayname(hiredate)='friday';
select timestampdiff(year,'2021-02-10','2024-02-06');
select timestampdiff(day,'2021-02-10','2024-02-06');
select quarter(now());
select round(1234.564,2);
select round(1234.564,1);
select round(1234.564,0);
select round(1234.564);
select round(1234.564,-1);
select round(1235.564,-1);
select round(1235.564,-2);
select round(1245.564,-2);
select concat(round(sum(sal)/1000),"K") from emp group by year(hiredate);
select truncate(1234.564,1);
select truncate(1234.564,0);
select truncate(1234.564);
select mod(2,2),2%2;
select mod(2,2),2+2;
select * from emp;
select sal from emp where ename='scott';
select ename from emp where sal>3000;
select * from emp where sal>(select sal from emp where ename='scott');
select ename from emp where sal>(select sal from emp where ename='scott');
select * from emp where sal=(select max(sal) from emp);
select * from emp where deptno=(select deptno from dept where dname = 'sales');
select * from dept;
select max(sal) from emp group by deptno;
select * from emp where sal in (select max(sal) from emp group by deptno);
select * from emp;
select ename as reporting_managers from emp where empno in (select mgr from emp);
select * from dept where deptno not in (select deptno from emp);